dist: bionic
language: php

php:
  - 7.3
  - 7.4

env:
  global:
    - setup=basic
    - coverage=no
  matrix:
    - laravel=^6.0
    - laravel=^7.0
    - laravel=^8.0
    - setup=stable laravel=^6.0
    - setup=stable laravel=^7.0
    - setup=stable laravel=^8.0
    - setup=lowest laravel=^6.0
    - setup=lowest laravel=^7.0
    - setup=lowest laravel=^8.0

before_install:
  - composer config discard-changes true

before_script:
  - composer require "laravel/framework=${laravel}" --prefer-dist --no-interaction --no-suggest
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --no-suggest --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --no-suggest --prefer-lowest --prefer-stable; fi
  - if [[ $setup = 'coveralls' ]]; then travis_retry composer require "php-coveralls/php-coveralls=^2.1" --prefer-dist --no-interaction --no-suggest --dev; fi

script:
  - if [[ $coverage = 'yes' ]]; then vendor/bin/phpunit -c phpunit.xml --coverage-clover build/logs/clover.xml; fi
  - if [[ $coverage = 'no' ]]; then vendor/bin/phpunit -c phpunit.xml; fi

after_script:
  - if [[ $setup = 'coveralls' ]]; then php vendor/bin/php-coveralls -v; fi

matrix:
  include:
    - php: 7.3
      env: setup=coveralls coverage=yes laravel=^6.0
  allow_failures:
    - env: setup=coveralls coverage=yes laravel=^6.0
  fast_finish: true
