dist: bionic
language: php

php:
  - 7.3
  - 7.4

env:
  global:
    - setup=basic
    - coverage=no
  matrix:
    - laravel=^8.0
    - setup=stable laravel=^8.0
    - setup=lowest laravel=^8.0

before_install:
  - composer config discard-changes true

before_script:
  - composer require "laravel/framework=${laravel}" --prefer-dist --no-interaction --no-update
  - if [[ $setup = 'basic' ]]; then travis_retry composer install --prefer-dist --no-interaction; fi
  - if [[ $setup = 'stable' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-stable; fi
  - if [[ $setup = 'lowest' ]]; then travis_retry composer update --prefer-dist --no-interaction --prefer-lowest --prefer-stable; fi
  - if [[ $setup = 'coveralls' ]]; then wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.2.0/php-coveralls.phar; chmod +x php-coveralls.phar; fi

script:
  - if [[ $coverage = 'yes' ]]; then vendor/bin/phpunit -c phpunit.xml --coverage-clover build/logs/clover.xml; fi
  - if [[ $coverage = 'no' ]]; then vendor/bin/phpunit -c phpunit.xml; fi

after_script:
  - if [[ $setup = 'coveralls' ]]; then php-coveralls.phar -v; fi

matrix:
  include:
    - php: 7.3
      env: setup=coveralls coverage=yes laravel=^8.0
  allow_failures:
    - env: setup=coveralls coverage=yes laravel=^8.0
  fast_finish: true
